FROM golang:1.24.2-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -o migrator ./cmd/migrator

FROM gcr.io/distroless/base-debian12
WORKDIR /app
COPY --from=builder /app/migrator /app/migrator
CMD ["/app/migrator"]