// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/grpcProto.proto

package grpcProto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Создать Карточку; Серверу
type CreateCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Userid        int64                  `protobuf:"varint,2,opt,name=userid,proto3" json:"userid,omitempty"`
	Deckid        int64                  `protobuf:"varint,3,opt,name=deckid,proto3" json:"deckid,omitempty"`
	Text1         string                 `protobuf:"bytes,4,opt,name=text1,proto3" json:"text1,omitempty"`
	Text2         string                 `protobuf:"bytes,5,opt,name=text2,proto3" json:"text2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCardRequest) Reset() {
	*x = CreateCardRequest{}
	mi := &file_proto_grpcProto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCardRequest) ProtoMessage() {}

func (x *CreateCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcProto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCardRequest.ProtoReflect.Descriptor instead.
func (*CreateCardRequest) Descriptor() ([]byte, []int) {
	return file_proto_grpcProto_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCardRequest) GetUserid() int64 {
	if x != nil {
		return x.Userid
	}
	return 0
}

func (x *CreateCardRequest) GetDeckid() int64 {
	if x != nil {
		return x.Deckid
	}
	return 0
}

func (x *CreateCardRequest) GetText1() string {
	if x != nil {
		return x.Text1
	}
	return ""
}

func (x *CreateCardRequest) GetText2() string {
	if x != nil {
		return x.Text2
	}
	return ""
}

// обновить карточку; Серверу
type UpdateCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cardid        int64                  `protobuf:"varint,1,opt,name=cardid,proto3" json:"cardid,omitempty"`
	Text1         string                 `protobuf:"bytes,4,opt,name=text1,proto3" json:"text1,omitempty"`
	Text2         string                 `protobuf:"bytes,5,opt,name=text2,proto3" json:"text2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCardRequest) Reset() {
	*x = UpdateCardRequest{}
	mi := &file_proto_grpcProto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCardRequest) ProtoMessage() {}

func (x *UpdateCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcProto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCardRequest.ProtoReflect.Descriptor instead.
func (*UpdateCardRequest) Descriptor() ([]byte, []int) {
	return file_proto_grpcProto_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateCardRequest) GetCardid() int64 {
	if x != nil {
		return x.Cardid
	}
	return 0
}

func (x *UpdateCardRequest) GetText1() string {
	if x != nil {
		return x.Text1
	}
	return ""
}

func (x *UpdateCardRequest) GetText2() string {
	if x != nil {
		return x.Text2
	}
	return ""
}

// Удалить карточку; Серверу
type DeleteCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cardid        int64                  `protobuf:"varint,1,opt,name=cardid,proto3" json:"cardid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCardRequest) Reset() {
	*x = DeleteCardRequest{}
	mi := &file_proto_grpcProto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCardRequest) ProtoMessage() {}

func (x *DeleteCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcProto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCardRequest.ProtoReflect.Descriptor instead.
func (*DeleteCardRequest) Descriptor() ([]byte, []int) {
	return file_proto_grpcProto_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteCardRequest) GetCardid() int64 {
	if x != nil {
		return x.Cardid
	}
	return 0
}

// Получить карточку; Серверу
type GetCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cardid        int64                  `protobuf:"varint,1,opt,name=cardid,proto3" json:"cardid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardRequest) Reset() {
	*x = GetCardRequest{}
	mi := &file_proto_grpcProto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardRequest) ProtoMessage() {}

func (x *GetCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcProto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardRequest.ProtoReflect.Descriptor instead.
func (*GetCardRequest) Descriptor() ([]byte, []int) {
	return file_proto_grpcProto_proto_rawDescGZIP(), []int{3}
}

func (x *GetCardRequest) GetCardid() int64 {
	if x != nil {
		return x.Cardid
	}
	return 0
}

// Получить много карточек; Серверу
type ListCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deckid        int64                  `protobuf:"varint,3,opt,name=deckid,proto3" json:"deckid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCardRequest) Reset() {
	*x = ListCardRequest{}
	mi := &file_proto_grpcProto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCardRequest) ProtoMessage() {}

func (x *ListCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcProto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCardRequest.ProtoReflect.Descriptor instead.
func (*ListCardRequest) Descriptor() ([]byte, []int) {
	return file_proto_grpcProto_proto_rawDescGZIP(), []int{4}
}

func (x *ListCardRequest) GetDeckid() int64 {
	if x != nil {
		return x.Deckid
	}
	return 0
}

// Отправить карточку; Клиенту
type CardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cardid        int64                  `protobuf:"varint,1,opt,name=cardid,proto3" json:"cardid,omitempty"`
	Userid        int64                  `protobuf:"varint,2,opt,name=userid,proto3" json:"userid,omitempty"`
	Deckid        int64                  `protobuf:"varint,3,opt,name=deckid,proto3" json:"deckid,omitempty"`
	Text1         string                 `protobuf:"bytes,4,opt,name=text1,proto3" json:"text1,omitempty"`
	Text2         string                 `protobuf:"bytes,5,opt,name=text2,proto3" json:"text2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardResponse) Reset() {
	*x = CardResponse{}
	mi := &file_proto_grpcProto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardResponse) ProtoMessage() {}

func (x *CardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcProto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardResponse.ProtoReflect.Descriptor instead.
func (*CardResponse) Descriptor() ([]byte, []int) {
	return file_proto_grpcProto_proto_rawDescGZIP(), []int{5}
}

func (x *CardResponse) GetCardid() int64 {
	if x != nil {
		return x.Cardid
	}
	return 0
}

func (x *CardResponse) GetUserid() int64 {
	if x != nil {
		return x.Userid
	}
	return 0
}

func (x *CardResponse) GetDeckid() int64 {
	if x != nil {
		return x.Deckid
	}
	return 0
}

func (x *CardResponse) GetText1() string {
	if x != nil {
		return x.Text1
	}
	return ""
}

func (x *CardResponse) GetText2() string {
	if x != nil {
		return x.Text2
	}
	return ""
}

// Получить ответ на Удаление карточки; Клиенту
type DeleteCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       string                 `protobuf:"bytes,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCardResponse) Reset() {
	*x = DeleteCardResponse{}
	mi := &file_proto_grpcProto_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCardResponse) ProtoMessage() {}

func (x *DeleteCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcProto_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCardResponse.ProtoReflect.Descriptor instead.
func (*DeleteCardResponse) Descriptor() ([]byte, []int) {
	return file_proto_grpcProto_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteCardResponse) GetSuccess() string {
	if x != nil {
		return x.Success
	}
	return ""
}

var File_proto_grpcProto_proto protoreflect.FileDescriptor

const file_proto_grpcProto_proto_rawDesc = "" +
	"\n" +
	"\x15proto/grpcProto.proto\x12\tgrpcProto\"o\n" +
	"\x11CreateCardRequest\x12\x16\n" +
	"\x06userid\x18\x02 \x01(\x03R\x06userid\x12\x16\n" +
	"\x06deckid\x18\x03 \x01(\x03R\x06deckid\x12\x14\n" +
	"\x05text1\x18\x04 \x01(\tR\x05text1\x12\x14\n" +
	"\x05text2\x18\x05 \x01(\tR\x05text2\"W\n" +
	"\x11UpdateCardRequest\x12\x16\n" +
	"\x06cardid\x18\x01 \x01(\x03R\x06cardid\x12\x14\n" +
	"\x05text1\x18\x04 \x01(\tR\x05text1\x12\x14\n" +
	"\x05text2\x18\x05 \x01(\tR\x05text2\"+\n" +
	"\x11DeleteCardRequest\x12\x16\n" +
	"\x06cardid\x18\x01 \x01(\x03R\x06cardid\"(\n" +
	"\x0eGetCardRequest\x12\x16\n" +
	"\x06cardid\x18\x01 \x01(\x03R\x06cardid\")\n" +
	"\x0fListCardRequest\x12\x16\n" +
	"\x06deckid\x18\x03 \x01(\x03R\x06deckid\"\x82\x01\n" +
	"\fCardResponse\x12\x16\n" +
	"\x06cardid\x18\x01 \x01(\x03R\x06cardid\x12\x16\n" +
	"\x06userid\x18\x02 \x01(\x03R\x06userid\x12\x16\n" +
	"\x06deckid\x18\x03 \x01(\x03R\x06deckid\x12\x14\n" +
	"\x05text1\x18\x04 \x01(\tR\x05text1\x12\x14\n" +
	"\x05text2\x18\x05 \x01(\tR\x05text2\".\n" +
	"\x12DeleteCardResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\tR\asuccess2\xe4\x02\n" +
	"\vCardService\x12C\n" +
	"\n" +
	"CreateCard\x12\x1c.grpcProto.CreateCardRequest\x1a\x17.grpcProto.CardResponse\x12C\n" +
	"\n" +
	"UpdateCard\x12\x1c.grpcProto.UpdateCardRequest\x1a\x17.grpcProto.CardResponse\x12I\n" +
	"\n" +
	"DeleteCard\x12\x1c.grpcProto.DeleteCardRequest\x1a\x1d.grpcProto.DeleteCardResponse\x12=\n" +
	"\aGetCard\x12\x19.grpcProto.GetCardRequest\x1a\x17.grpcProto.CardResponse\x12A\n" +
	"\bListCard\x12\x1a.grpcProto.ListCardRequest\x1a\x17.grpcProto.CardResponse0\x01B\x1bZ\x19proto/grpcProto;grpcProtob\x06proto3"

var (
	file_proto_grpcProto_proto_rawDescOnce sync.Once
	file_proto_grpcProto_proto_rawDescData []byte
)

func file_proto_grpcProto_proto_rawDescGZIP() []byte {
	file_proto_grpcProto_proto_rawDescOnce.Do(func() {
		file_proto_grpcProto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_grpcProto_proto_rawDesc), len(file_proto_grpcProto_proto_rawDesc)))
	})
	return file_proto_grpcProto_proto_rawDescData
}

var file_proto_grpcProto_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_grpcProto_proto_goTypes = []any{
	(*CreateCardRequest)(nil),  // 0: grpcProto.CreateCardRequest
	(*UpdateCardRequest)(nil),  // 1: grpcProto.UpdateCardRequest
	(*DeleteCardRequest)(nil),  // 2: grpcProto.DeleteCardRequest
	(*GetCardRequest)(nil),     // 3: grpcProto.GetCardRequest
	(*ListCardRequest)(nil),    // 4: grpcProto.ListCardRequest
	(*CardResponse)(nil),       // 5: grpcProto.CardResponse
	(*DeleteCardResponse)(nil), // 6: grpcProto.DeleteCardResponse
}
var file_proto_grpcProto_proto_depIdxs = []int32{
	0, // 0: grpcProto.CardService.CreateCard:input_type -> grpcProto.CreateCardRequest
	1, // 1: grpcProto.CardService.UpdateCard:input_type -> grpcProto.UpdateCardRequest
	2, // 2: grpcProto.CardService.DeleteCard:input_type -> grpcProto.DeleteCardRequest
	3, // 3: grpcProto.CardService.GetCard:input_type -> grpcProto.GetCardRequest
	4, // 4: grpcProto.CardService.ListCard:input_type -> grpcProto.ListCardRequest
	5, // 5: grpcProto.CardService.CreateCard:output_type -> grpcProto.CardResponse
	5, // 6: grpcProto.CardService.UpdateCard:output_type -> grpcProto.CardResponse
	6, // 7: grpcProto.CardService.DeleteCard:output_type -> grpcProto.DeleteCardResponse
	5, // 8: grpcProto.CardService.GetCard:output_type -> grpcProto.CardResponse
	5, // 9: grpcProto.CardService.ListCard:output_type -> grpcProto.CardResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_grpcProto_proto_init() }
func file_proto_grpcProto_proto_init() {
	if File_proto_grpcProto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_grpcProto_proto_rawDesc), len(file_proto_grpcProto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_grpcProto_proto_goTypes,
		DependencyIndexes: file_proto_grpcProto_proto_depIdxs,
		MessageInfos:      file_proto_grpcProto_proto_msgTypes,
	}.Build()
	File_proto_grpcProto_proto = out.File
	file_proto_grpcProto_proto_goTypes = nil
	file_proto_grpcProto_proto_depIdxs = nil
}
